version: "3"

services:
  db:
    restart: always
    image: postgres:9.6-alpine
    shm_size: 256mb
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:6.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

  web:
    image: sekai/mastodon
    restart: always
    env_file: .env.production
    command: sh -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    image: sekai/mastodon
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    depends_on:
      - db
      - redis

  sidekiq:
    image: sekai/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 443:443
    depends_on:
      - web
      - streaming
    networks:
      - external_network
    volumes:
      - ./tls:/etc/nginx/tls:ro
      - ./nginx:/etc/nginx/conf.d:ro
      - ./public/system:/home/mastodon/live/public/system:ro

networks:
  external_network:
  internal_network:
    internal: true
