- hostname:
    name: Pamela

- pacman:
    state: latest
    update_cache: yes
    name:
      - docker
      - docker-compose
      - fish
      - git
      - python
      - rsync
      - sudo

- systemd:
    state: started
    enabled: yes
    name: "{{item}}"
  loop:
    - docker

- ini_file:
    path: /etc/mkinitcpio.conf
    section: null
    option: MODULES
    value: (bcm_phy_lib broadcom mdio_bcm_unimac genet)
