- hosts: all
  become: yes
  tasks:
    - import_tasks: tasks/base.yml
      tags: base
    - import_tasks: tasks/network.yml
      tags: network
    - import_tasks: tasks/user.yml
      tags: user
      vars:
        user: kaz
    - import_tasks: tasks/unifi.yml
      tags: unifi
    - import_tasks: tasks/mastodon.yml
      tags: mastodon
